Month9/step2
HebrinJ/react-stellar-burger pull request #6
Opened 2023-11-21 08:50 UTC by HebrinJ

Реализован функционал в соответствии заданием

2023-11-21 10:55 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/7SQzEBFy1-JgbQ>; А то может произойти такая ситуация: <https://disk.yandex.com/i/RLWcWimvmea9rw>, цена не соответствует количеству ингредиентов;

- <https://disk.yandex.com/i/6VuOb-JQRzEoLg>, у вас бесконечно создаются сокет соединения, должно создаваться только 1 раз.

- При открытии модальных окон "Детали ингредиента" у вас вызывается запрос `GET /ingredients`, лучше чтобы он вызывался 1 раз. (Добавьте вызов в компонент app, а остальные уберите).

По чек-листу требуется:

- Написать middleware, который принимает на вход параметр URL сокет-соединения и содержит набор обработчиков событий: onmessage, onclose, onerror, send.
- А также логика подключения к сокет-соединению, получение сообщений с помощью него и обработка ошибок должна быть реализована с использованием библиотеки Redux.
- Для каждого типа события описаны экшены.
- Для работы с WebSocket описано базовое состояние Store и создан редьюсер.

Советую обратиться за помощью к наставнику, чтобы правильно всё реализовать)

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/app-header/appHeader.jsx
>      }
**Надо исправить:**

иконка тоже должна быть обёрнута в ссылку, поэтому используйте `isActive` для определения нужного типа для иконки.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +        } />
**Можно лучше:**

`element` вроде бы одинаковый, может быть стоит вынести в отдельную страницу, и переиспользовать?)

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/feed/orders-state/state-panel/statePanel.jsx
> +                })}
**Надо исправить:**

Здесь и далее.

почему бы не использовать `order.number`, он вроде бы уникален для каждого заказа.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/modals/modal-window.jsx
> +        if(modalType === 'info' || modalType === 'order-info') {
**Можно лучше:**

лучше вынести в массив и проверять через `includes`, так будет более читабельнее и в случае чего можно увеличить список)) 
```js
const isModalTypeInfo = ['info', 'order-info'].includes(modalType);

if (isModalTypeInfo) {...}
```

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/order-details/orderDetails.jsx
> +    orderDetails = storeOrder
**Надо исправить:**

вы не должны мутировать объекты в реакте. Создайте новую переменную или используйте `useState`.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/order-details/orderDetails.jsx
> +                        return <IngredientList product={getDetails(id)} amount={amount} key={key} />
**Надо исправить:**

у каждого ингредиента есть `id` используйте его в качестве `key`

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/order-details/orderDetails.jsx
> +                <FormattedDate className='text text_type_main-default text_color_inactive' date={new Date(orderDetails.createdAt)} />
**Можно лучше:**

лучше вынести в отдельную переменную.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/orders/order-card/orderCard.jsx
> +                    return <OrderItemsFeed id={id} position={ingredients.length - index} key={key}/>
**Рекомендую исправить:**

Условия `id === null` и `index > 5` можно объединить `id === null || index > 5`.

Условие `index === 5` избыточно. 

А также запись 

```js
number={`+${number.toString()}`}
```

можно сократить до 

```js 
number={`+${number}`} 
```

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/orders/orders.jsx
> +}, [socketUrl, isPersonal, orders])
**Надо исправить:**

тут вообще не нужны зависимости, оставьте `[]`. Из-за `orders` у вас бесконечно открываются сокет соединения.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/orders/orders.jsx
> +        })}
**Надо исправить:**

Тут разница только в массивав, до рендера сделаете условие и выберите нужный массив.

```js
const currentOrders =  isPersonal ? userOrders : orders;

return (...)
```

И используйте `order._id` в качестве `key`, старайтесь использовать уже имеющиеся данные, а не совмещать их.

2023-11-21 10:55 UTC, ArslanMustafin commented on src/components/orders/orders.jsx
> +    }
**Надо исправить:**

По чек-листу требуется: 

- Написать middleware, который принимает на вход параметр URL сокет-соединения и содержит набор обработчиков событий: onmessage, onclose, onerror, send.
- А также логика подключения к сокет-соединению, получение сообщений с помощью него и обработка ошибок должна быть реализована с использованием библиотеки Redux. 
- Для каждого типа события описаны экшены.
- Для работы с WebSocket описано базовое состояние Store и создан редьюсер.

Советую обратиться за помощью к наставнику, чтобы правильно всё реализовать)

2023-11-22 16:40 UTC, HebrinJ commented on src/components/orders/order-card/orderCard.jsx
> +                    return <OrderItemsFeed id={id} position={ingredients.length - index} key={key}/>
Если убрать index === 5, то цифры с количеством ингредиентов сверх шести, будет появляться на всех ингредиентах.

2023-11-23 11:27 UTC, ArslanMustafin commented on src/components/orders/order-card/orderCard.jsx
> +                    return <OrderItemsFeed id={id} position={ingredients.length - index} key={key}/>
Понял), тогда оставляем условие.

2023-11-23 12:06 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!÷**

- Все замечания были исправлены;

### **Сделает код лучше:**

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/7SQzEBFy1-JgbQ>, это нужно чтобы порядок элементов в заказе был верным;

2023-11-23 12:06 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +          <Route path={path} element={background ? (<ModalWindow><ModalSetter /></ModalWindow>) : (<OrderDetailsPage />)} key={index} />
**Можно лучше:**

я имелл виду вынести вот это `background ? (<ModalWindow><ModalSetter /></ModalWindow>) : (<OrderDetailsPage />)` в отдельный компонент)) а остальное лучше оставить как было

2023-11-23 12:06 UTC, ArslanMustafin commented on src/pages/mainPage.jsx
> +        dispatch(getIngredientsData());
**Рекомендую исправить:**

Оставьте просто вызов в `app.js` без условий. Тоже самое касается и получения данных пользователя.

```js
React.useEffect(() => {
    dispatch(getIngredientsData());
    
     if(localStorage.getItem('accessToken')) {
        dispatch(getUser());
    }       
})
```

2023-11-29 12:31 UTC, merged